[browser]
gatherUsageStats = false

[server]
headless = true

[theme]
primaryColor = "#0EA5E9"
backgroundColor = "#F0F4F8"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0F172A"
font = "sans serif"
